### ISSUE TITLE
PlayersController Issue

### ISSUE THREAD

**Issue by koopaluigi** [YCPCS-481-TeamB/BaseballSim#26]
Going through the tests I wasn't sure which _[id](https://github.com/YCPCS-481-TeamB/BaseballSim/blob/8aec533d2fbce00e50c00e3d3e5aa3a1180fb24a/Controller/PlayersController.js#L64)_ this function was referring to, team_id or player_id. If it is referring to player_id, then it should be returning the player with _[resolve(data.rows[0]);](https://github.com/YCPCS-481-TeamB/BaseballSim/blob/8aec533d2fbce00e50c00e3d3e5aa3a1180fb24a/Controller/PlayersController.js#L67)_ instead of an array.

```javascript
/**
 * Returns a promise that contains an array of the players with the requested id
 * @param id
 * @returns {Promise}
 */
exports.getPlayersById = function(id){
    return new Promise(function(resolve, reject){
        DatabaseController.query("SELECT * from players WHERE id = $1", [id]).then(function(data){
            resolve(data.rows);
        });
    });
}
```

**Comment by bfwalton** [comment]
Updated the Controller to only pull the player, added error checking to return an error when the player doesn't exist, and Comments to be more clear

Updated in Commit 5e7e8c4
