### ISSUE TITLE
API does not return appropriate HTTP status codes

### ISSUE THREAD

**Issue by bcoov** [YCPCS-481-TeamB/BaseballSim#30]
The API currently returns an HTTP 200 status code as a response when obtaining data, whether the requester is authenticated or not. Is there a way to have the API return appropriate codes for the situation? In this case, an [HTTP 401 code](https://httpstatuses.com/401) would be expected.

**Comment by bfwalton** [comment]
Issue resolved for that specific situation in commit 45086355d1498a77bbb13cf258813baeb74444d5

This change is only reflected in the development branch for now because the version on heroku needs updated database tables for full functionality.
