### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by bcoov** [YCPCS-481-TeamB/BaseballSim#62]
#29 is a good start to understanding how to use the API, but more detailed API documentation is sorely needed. Specifically what values/fields are required (if any) when performing operations to the various endpoints.

**Comment by sfitzpa4** [comment]
What operations are you trying to do on these endpoints, an example perhaps?

**Comment by sfitzpa4** [comment]
Here's an updated Endpoints Doc
[API.Endpoints.docx](https://github.com/YCPCS-481-TeamB/BaseballSim/files/593250/API.Endpoints.docx)

**Comment by bcoov** [comment]
I was hoping for something resembling typical API documentation (The [GitHub API docs](https://developer.github.com/guides/getting-started/#issues) are a good example)

So for authenticating, I'd expect something like this:

## Authentication
To authenticate a user, perform a POST to the /users/token/ endpoint.
- Required Headers
    - "Content-Type": "application/x-www-form-urlencoded"
- Required parameters (where format is: "param1=value1&param2=value2&...")
    - "username": username for the user to authenticate
    - "password": that user's password

The reply to this operation will include a "success" element indicating "true" or "false on whether the authentication succeeded. If it did, there will also be a "token" element, whose value is the authentication token to be passed with future HTTP operations to indicate an authenticated operation.

**Comment by sfitzpa4** [comment]
API Documentation is found in the Dev branch here: [https://github.com/YCPCS-481-TeamB/BaseballSim/blob/Development/Database/gamesAPIDocs.txt](url)
